-- DB 생성
CREATE DATABASE appmgmt
CHARACTER SET = 'utf8'
COLLATE = 'utf8_general_ci';

-- 계정 추가
CREATE USER 'pofo'@'%' IDENTIFIED BY 'pofo1234';

-- 권한 추가
GRANT ALL PRIVILEGES ON appmgmt.* TO 'pofo1234'@'%';

-- 데이터베이스 변경
USE DATABASE appmgmt;

-- 테이블 추가
CREATE TABLE `TBL_CMM_CD_M` (
	`CMM_CD_GRP_ID`	VARCHAR(50)	NOT NULL	COMMENT '공통코드그룹아이디',
	`CMM_CD_GRP_NM`	VARCHAR(100)	NULL	DEFAULT NULL	COMMENT '공통코드그룹명',
	`CMM_CD_GRP_DSC`	VARCHAR(1000)	NULL	DEFAULT NULL	COMMENT '공통코드그룹설명',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);


CREATE TABLE `TBL_CMM_CD_D` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`CMM_CD_GRP_ID`	VARCHAR(50)	NOT NULL	COMMENT '공통코드그룹아이디',
	`CMM_CD`	VARCHAR(10)	NOT NULL	COMMENT '공통코드',
	`CMM_CD_NM`	VARCHAR(100)	NULL	DEFAULT NULL	COMMENT '공통코드명',
	`CMM_CD_DSC`	VARCHAR(1000)	NULL	DEFAULT NULL	COMMENT '공통코드설명',
	`SORT_SQNC`	INT(2)	NULL	DEFAULT NULL	COMMENT '정렬순서',
	`REFR_ID1`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '참조아이디1',
	`REFR_ID2`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '참조아이디2',
	`REFR_ID3`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '참조아이디3',
	`REFR_ID4`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '참조아이디4',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `TBL_USER_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`USER_NM`	VARCHAR(20)	NULL	DEFAULT NULL	COMMENT '사용자명',
	`EML_ADDR`	VARCHAR(100)	NULL	DEFAULT NULL	COMMENT '이메일주소',
	`PWD`	VARCHAR(256)	NULL	DEFAULT NULL	COMMENT '비밀번호',
	`CLPH_NUM`	VARCHAR(15)	NULL	DEFAULT NULL	COMMENT '휴대전화번호',
	`USER_TYPE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '사용자유형코드',
	`USER_STAT_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '사용자상태코드',
	`RCNT_LGN_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '최근로그인일시',
	`PWD_FAIL_CNT`	INT(2)	NOT NULL	DEFAULT 0	COMMENT '비밀번호실패횟수',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시',
	`PRFL_FILE_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '프로필파일번호'
);

CREATE TABLE `TBL_POFO_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`TITL_FILE_NUM`	INT(10)	NOT NULL	COMMENT '대표파일번호',
	`POFO_NM`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '포트폴리오명',
	`POFO_CATE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '포트폴리오카테고리코드',
	`POFO_VIEW_CNT`	INT(10)	NULL	DEFAULT NULL	COMMENT '포트폴리오조회수',
	`POFO_DSC`	VARCHAR(2000)	NULL	DEFAULT NULL	COMMENT '포트폴리오설명',
	`VIEW_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '공개여부',
	`WATER_MARK_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '워터마크여부',
	`BACK_CLR_VAL`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '배경색값',
	`CTNT_ITVL`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '콘텐츠간격',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `TBL_POFO_D` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오번호',
	`POFO_CTNT_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '포트폴리오콘텐츠코드',
	`FULL_SIZE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '전체크기여부',
	`SORT_SQNC`	INT(2)	NULL	DEFAULT NULL	COMMENT '정렬순서',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `TBL_POFO_IMG_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_DTL_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오상세번호',
	`FILE_NUM`	INT(10)	NOT NULL	COMMENT '파일번호'
);

CREATE TABLE `TBL_POFO_TXT_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_DTL_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오상세번호',
	`TXT_CTTS`	VARCHAR(2000)	NULL	DEFAULT NULL	COMMENT '텍스트내용'
);

CREATE TABLE `TBL_POFO_POTO_GRID_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_DTL_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오상세번호'
);

CREATE TABLE `TBL_POFO_VDO_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_DTL_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오상세번호',
	`FILE_NUM`	INT(10)	NOT NULL	COMMENT '파일번호',
	`AUTO_PLAY_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '자동재생여부'
);

CREATE TABLE `TBL_POFO_ADO_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_DTL_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오상세번호',
	`FILE_NUM`	INT(10)	NOT NULL	COMMENT '파일번호'
);

CREATE TABLE `TBL_POFO_LIKE_M` (
	`USER_NUM`	INT(10)	NOT NULL	COMMENT '사용자번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오번호',
	`LIKE_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '평가일시'
);

CREATE TABLE `TBL_MDBD_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`USER_NUM`	INT(10)	NOT NULL	COMMENT '사용자번호',
	`MDBD_NM`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '무드보드명',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `TBL_MDBD_D` (
	`MDBD_NUM`	INT(10)	NOT NULL	COMMENT '무드보드번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시'
);

CREATE TABLE `TBL_POFO_CMMT_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`USER_NUM`	INT(10)	NOT NULL	COMMENT '사용자번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오번호',
	`CMMT_CTTS`	VARCHAR(1000)	NULL	DEFAULT NULL	COMMENT '댓글내용',
	`CMMT_STAT_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '댓글상태코드',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `TBL_USER_POFO_MAP` (
	`USER_NUM`	INT(10)	NOT NULL	COMMENT '사용자번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오번호'
);

CREATE TABLE `TBL_POFO_TAG_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '포트폴리오번호',
	`TAG_NM`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '태그명',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시'
);

CREATE TABLE `TBL_POFO_USE_TOOL_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POFO_NUM`	INT(10)	NOT NULL	COMMENT '일련번호',
	`USE_TOOL_NM`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '사용툴명',
	`USE_TOOL_TYPE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '사용툴타입코드',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시'
);

CREATE TABLE `TBL_FILE_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`FILE_PATH`	VARCHAR(200)	NULL	DEFAULT NULL	COMMENT '파일경로',
	`FILE_NM`	VARCHAR(100)	NULL	DEFAULT NULL	COMMENT '파일명',
	`ORG_FILE_NM`	VARCHAR(100)	NULL	DEFAULT NULL	COMMENT '원본파일명',
	`FILE_TYPE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '파일타입코드',
	`FILE_SIZE`	VARCHAR(100)	NULL	DEFAULT NULL	COMMENT '파일크기',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `TBL_POFO_POTO_GRID_D` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`POTO_GRID_NUM`	INT(10)	NOT NULL	COMMENT '포토그리드번호',
	`FILE_NUM`	INT(10)	NOT NULL	COMMENT '파일번호',
	`GRID_WIDTH`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '그리드가로'
);

CREATE TABLE `POFO_CATE_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`CATE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '카테고리코드',
	`HRNK_CATE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '상위카테고리코드',
	`CATE_NM`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '카테고리명',
	`DEPTH`	INT(2)	NULL	DEFAULT NULL	COMMENT '뎁스',
	`SORT_SQNC`	INT(2)	NULL	DEFAULT NULL	COMMENT '정렬순서',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

CREATE TABLE `USE_TOOL_TYPE_M` (
	`SERS_NUM`	INT(10)	NOT NULL AUTO_INCREMENT	COMMENT '일련번호',
	`TYPE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '타입코드',
	`PART_TYPE_CD`	VARCHAR(10)	NULL	DEFAULT NULL	COMMENT '부모타입코드',
	`TYPE_NM`	VARCHAR(50)	NULL	DEFAULT NULL	COMMENT '타입명',
	`DEPTH`	INT(2)	NULL	DEFAULT NULL	COMMENT '뎁스',
	`SORT_SQNC`	INT(2)	NULL	DEFAULT NULL	COMMENT '정렬순서',
	`USE_YN`	TINYINT(4)	NOT NULL	DEFAULT 1	COMMENT '사용여부',
	`RGSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '등록자번호',
	`REG_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '등록일시',
	`UPSR_NUM`	INT(10)	NULL	DEFAULT NULL	COMMENT '수정자번호',
	`UPDT_DT`	DATETIME	NULL	DEFAULT NULL	COMMENT '수정일시'
);

ALTER TABLE `TBL_CMM_CD_M` ADD CONSTRAINT `PK_TBL_CMM_CD_M` PRIMARY KEY (
	`CMM_CD_GRP_ID`
);

ALTER TABLE `TBL_CMM_CD_D` ADD CONSTRAINT `PK_TBL_CMM_CD_D` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_USER_M` ADD CONSTRAINT `PK_TBL_USER_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_M` ADD CONSTRAINT `PK_TBL_POFO_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_D` ADD CONSTRAINT `PK_TBL_POFO_D` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_IMG_M` ADD CONSTRAINT `PK_TBL_POFO_IMG_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_TXT_M` ADD CONSTRAINT `PK_TBL_POFO_TXT_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_POTO_GRID_M` ADD CONSTRAINT `PK_TBL_POFO_POTO_GRID_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_VDO_M` ADD CONSTRAINT `PK_TBL_POFO_VDO_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_ADO_M` ADD CONSTRAINT `PK_TBL_POFO_ADO_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_MDBD_M` ADD CONSTRAINT `PK_TBL_MDBD_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_CMMT_M` ADD CONSTRAINT `PK_TBL_POFO_CMMT_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_TAG_M` ADD CONSTRAINT `PK_TBL_POFO_TAG_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_USE_TOOL_M` ADD CONSTRAINT `PK_TBL_POFO_USE_TOOL_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_FILE_M` ADD CONSTRAINT `PK_TBL_FILE_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_POFO_POTO_GRID_D` ADD CONSTRAINT `PK_TBL_POFO_POTO_GRID_D` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `POFO_CATE_M` ADD CONSTRAINT `PK_POFO_CATE_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `USE_TOOL_TYPE_M` ADD CONSTRAINT `PK_USE_TOOL_TYPE_M` PRIMARY KEY (
	`SERS_NUM`
);

ALTER TABLE `TBL_CMM_CD_D` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_USER_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_MDBD_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_CMMT_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_D` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_IMG_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_TXT_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_POTO_GRID_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_POTO_GRID_D` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_VDO_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_ADO_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_CMMT_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_TAG_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_POFO_USE_TOOL_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `TBL_FILE_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `POFO_CATE_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;

ALTER TABLE `USE_TOOL_TYPE_M` MODIFY `SERS_NUM` INT NOT NULL AUTO_INCREMENT;
